### ISSUE TITLE
Suffixes in Space Center don’t follow through.

### ISSUE THREAD

**Issue by frankrolf** [LettError/editThatNextMaster#5]
I just found out the Space Center can be influenced through a “suffix” menu (clicking on the cog on the top right → Suffix → Suffix of choice.) That’s handy for viewing the spacing of Small Caps for instance, without changing the spacing string.

This suffix setting currently doesn’t carry through to “that previous/next Space Center”.
(note this glyph name suffix is different than the spacing string “suffix” as identified in the code here:
https://github.com/LettError/editThatNextMaster/blob/master/editThatPreviousMaster.py#L73)

I’d gladly fix this myself and send a PR (the suffix string can be obtained through `SpaceCenter.getSuffix()`), but how can it be applied to the new space center?

Perhaps a question @typemytype could answer? 

Thanks!

**Comment by typemytype** [comment]
ooh, no `setSuffix` yet...

**Comment by LettError** [comment]
Any followup on this? Would be nice to have :)

**Comment by frankrolf** [comment]
@typemytype 
> Any followup on this? Would be nice to have :)

Indeed!

**Comment by typemytype** [comment]
`spaceCenter.setSuffix(...)` is idd missing in RF1.8 but already implemented in RF2.0 beta


hope this helps
